name: superlinter CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: gcc
      run: gcc --version
    - uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '6-2017-q1' # The arm-none-eabi-gcc release to use.
    - name: arm-none-eabi-gcc
      run: arm-none-eabi-gcc --version
    - name: make all
      run: make all
    - name: unit test
      run: ./stm32_application/build/utest
